In [1]:
import numpy as np

A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [5]:
print (B.shape) 

(4, 1)


In [4]:
print (A)

[[ 7.58315193e-01  1.23472474e+00  5.39222448e-01]
 [ 1.60828933e+00  7.54911628e-03 -9.31642352e-01]
 [ 1.08820059e+00  9.79286311e-04  6.88337619e-02]
 [-1.56571994e+00  1.27464368e+00  1.63603384e+00]]
